version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: lab3
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: nest_api
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    environment:
      DATABASE_URL: 'postgresql://postgres:admin@localhost:5432/lab3?schema=public'

volumes:
  postgres_data:
